### ISSUE TITLE
Cambiando Footer

### ISSUE THREAD

**Issue by RicaraSecas** [CeliaAlonso/RepositorioWebDAW#2]
Voy a cambiar el footer a uno que no da tanto asco y esta todo mejor distribuido.
Ahora lo subo y opináis.

**Comment by davidgomezq** [comment]
He tenido que borrar el footer en el ultimo commit Ricar.

Estaba dando problemas con el responsive de los moviles y en el PC el responsive iba perfecto, me he vuelto loco buscando el porque y no lo he resuelto.

Yo optaria por hacer un footer a mano con bootstrap y sus columnas, que tuviese como mucho 150px de alto y listo, asi no tenemos problemas con las importancias del header y de footer.

**Comment by RicaraSecas** [comment]
Ok, mañana me pongo a ello!

**Comment by davidgomezq** [comment]
Ricar, te he puesto la estructura del footer, falta el contenido de el. La he puesto para posicionar el main.
